# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PingPong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PingPong
  pod "Tibei"

end

target 'PingPongtvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PingPongtvOS

end
